---
# tasks file for azure_pipelines_agent-ctl
- name: install dependencies
  when: azure_pipelines_agent_ctl_install_dependencies
  command:
    chdir: '{{ azure_pipelines_agent_ctl_install_dir }}'
    cmd: '{{ azure_pipelines_agent_ctl_dependency_install_script }}'
  tags: install-deps

- name: configure web proxy
  when: azure_pipelines_agent_ctl_proxy.url is defined
  block:
    - name: write {{ azure_pipelines_agent_ctl_install_dir }}/.proxy
      template:
        src: .proxy.j2
        dest: '{{ azure_pipelines_agent_ctl_install_dir }}/.proxy'
        mode: 0644
    - name: write {{ azure_pipelines_agent_ctl_install_dir }}/.proxybypass
      when: azure_pipelines_agent_ctl_proxy.bypass is defined
      template:
        src: .proxybypass.j2
        dest: '{{ azure_pipelines_agent_ctl_install_dir }}/.proxybypass'
        mode: 0644
  tags: configure

- name: write {{ azure_pipelines_agent_ctl_install_dir }}/.env
  when: azure_pipelines_agent_ctl_job_base_env is defined
  blockinfile:
    create: yes
    dest: '{{ azure_pipelines_agent_ctl_install_dir }}/.env'
    mode: 0644
    state: present
    block: |
      {%- for k, v in azure_pipelines_agent_ctl_job_base_env.items() -%}
      {{ k }}={{ v }}
      {% endfor -%}
  tags: configure

- name: register agent
  command:
    chdir: '{{ azure_pipelines_agent_ctl_install_dir }}'
    cmd: '{{ azure_pipelines_agent_ctl_register_agent_cmd }}'
    creates: '{{ azure_pipelines_agent_ctl_install_dir }}/(.agent,.credentials)'
  environment: '{{ azure_pipelines_agent_ctl_shell_env }}'
  tags: configure

- name: initialize {{ azure_pipelines_agent_ctl_init_service_type }} service
  include_tasks: '{{ azure_pipelines_agent_ctl_init_service_type }}.yml'
  tags: service

- name: remove agent
  command:
    chdir: '{{ azure_pipelines_agent_ctl_install_dir }}'
    cmd: '{{ azure_pipelines_agent_ctl_remove_agent_cmd }}'
    removes: '{{ azure_pipelines_agent_ctl_install_dir }}/(.agent,.credentials)'
  environment: '{{ azure_pipelines_agent_ctl_shell_env }}'
  tags: unregister
