---
# tasks file for azure_pipelines_agent-ctl
- name: install dependencies
  when: azure_pipelines_agent_ctl_install_dependencies
  shell:
    chdir: '{{ azure_pipelines_agent_ctl_install_dir }}'
    cmd: '{{ azure_pipelines_agent_ctl_dependency_install_script }}'
    executable: /bin/bash
  tags: install-deps
  
- name: register agent
  shell:
    chdir: '{{ azure_pipelines_agent_ctl_install_dir }}'
    cmd: '{{ azure_pipelines_agent_ctl_register_agent_cmd }}'
    executable: /bin/bash
  environment: '{{ azure_pipelines_agent_ctl_shell_env }}'
  tags: configure

- name: initialize {{ azure_pipelines_agent_ctl_init_service_type }} service
  include_tasks: '{{ azure_pipelines_agent_ctl_init_service_type }}.yml'
  tags: service

- name: remove agent
  shell: 
    chdir: '{{ azure_pipelines_agent_ctl_install_dir }}'
    cmd: '{{ azure_pipelines_agent_ctl_remove_agent_cmd }}'
    executable: /bin/bash
  environment: '{{ azure_pipelines_agent_ctl_shell_env }}'
  tags: unregister
