---
# tasks file for azure_pipelines_agent-ctl
- name: install dependencies
  when: azure_pipelines_agent_ctl_install_dependencies
  command:
    chdir: '{{ azure_pipelines_agent_ctl_install_dir }}'
    cmd: '{{ azure_pipelines_agent_ctl_dependency_install_script }}'
  tags: install-deps

- name: register agent
  command:
    chdir: '{{ azure_pipelines_agent_ctl_install_dir }}'
    cmd: '{{ azure_pipelines_agent_ctl_register_agent_cmd }}'
    creates: '{{ azure_pipelines_agent_ctl_install_dir }}/(.agent,.credentials)'
  environment: '{{ azure_pipelines_agent_ctl_shell_env }}'
  tags: configure

- name: initialize {{ azure_pipelines_agent_ctl_init_service_type }} service
  include_tasks: '{{ azure_pipelines_agent_ctl_init_service_type }}.yml'
  tags: service

- name: remove agent
  command:
    chdir: '{{ azure_pipelines_agent_ctl_install_dir }}'
    cmd: '{{ azure_pipelines_agent_ctl_remove_agent_cmd }}'
    removes: '{{ azure_pipelines_agent_ctl_install_dir }}/(.agent,.credentials)'
  environment: '{{ azure_pipelines_agent_ctl_shell_env }}'
  tags: unregister
