---
- name: refresh service environment
  command:
    chdir: '{{ azure_pipelines_agent_ctl_install_dir }}'
    cmd: '{{ azure_pipelines_agent_ctl_env_script }}'
    creates: '{{ azure_pipelines_agent_ctl_install_dir }}/(.env,.path)'
  environment: '{{ azure_pipelines_agent_ctl_shell_env }}'
  tags: configure

- name: initialize systemd service
  become: yes
  become_user: '{{ azure_pipelines_agent_ctl_service_user }}'
  command:
    chdir: '{{ azure_pipelines_agent_ctl_install_dir }}'
    cmd: '{{ azure_pipelines_agent_ctl_svc_install_cmd }}'
    creates: '{{ azure_pipelines_agent_ctl_install_dir }}/(runsvc.sh,.service)'
  tags: configure

- name: start systemd service
  become: yes
  become_user: '{{ azure_pipelines_agent_ctl_service_user }}'
  command:
    chdir: '{{ azure_pipelines_agent_ctl_install_dir }}'
    cmd: '{{ azure_pipelines_agent_ctl_svc_start_cmd }}'
  tags: init

- name: stop systemd service
  become: yes
  become_user: '{{ azure_pipelines_agent_ctl_service_user }}'
  command:
    chdir: '{{ azure_pipelines_agent_ctl_install_dir }}'
    cmd: '{{ azure_pipelines_agent_ctl_svc_stop_cmd }}'
  tags:
    - shutdown
    - unregister

- name: uninstall systemd service
  become: yes
  become_user: '{{ azure_pipelines_agent_ctl_service_user }}'
  command:
    chdir: '{{ azure_pipelines_agent_ctl_install_dir }}'
    cmd: '{{ azure_pipelines_agent_ctl_svc_uninstall_cmd }}'
    removes: '{{ azure_pipelines_agent_ctl_install_dir }}/(runsvc.sh,.service)'
  tags:
    - unregister
